- hosts: k8s
  tasks:
    - name: set k8s 源
      shell:
        cmd: |
          cat <<EOF > /etc/yum.repos.d/kubernetes.repo
          [kubernetes]
          name=Kubernetes
          baseurl=http://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=0
          repo_gpgcheck=0
          gpgkey=http://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg
                http://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
          EOF
    - name: 卸载旧版本 安装kubelet、kubeadm、kubectl
      shell:
        cmd: | 
          yum remove -y kubelet kubeadm kubectl
          yum install -y kubelet-1.16.0 kubeadm-1.16.0 kubectl-1.16.0
    - name: 设置 docker 镜像，提高 docker 镜像下载速度和稳定性
      shell:
        cmd: |
          curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://f1361db2.m.daocloud.io
    - name: 修改 docker cgroup driver 为 systemd
      shell:
        cmd: |
          sed -i "s#^ExecStart=/usr/bin/dockerd.*#ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd#g" /usr/lib/systemd/system/docker.service
    - name: 重新加载 systemctl
      shell:
        cmd: |
          systemctl daemon-reload
    - name: restart docker
      systemd:
        state: restarted
        name: docker
        enabled: yes
    - name: restart kubelet
      systemd:
        state: restarted
        name: kubelet
        enabled: yes
    