- hosts: master
  tasks:
    - name: kubeadm config images pull
      shell:
        cmd: |
          kubeadm config images pull --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers
    - name: kubeadm init
      shell:
        cmd: | 
          kubeadm init --apiserver-advertise-address=10.6.208.11 --apiserver-bind-port=6443 --control-plane-endpoint=10.6.208.100:16443 --kubernetes-version v1.16.1 --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers --service-cidr=10.96.0.0/16
      register: kubeadm_result
    - name: show kubeadm_result debug info 
      debug: var=kubeadm_result verbosity=0
    - name: kubectl 配置
      shell:
        cmd: |
          rm -rf /root/.kube/
          mkdir /root/.kube/
          cp -i /etc/kubernetes/admin.conf /root/.kube/config
    - name: 安装 calico 网络插件
      shell:
        cmd: |
          rm -f calico.yaml
          wget https://docs.projectcalico.org/v3.8/manifests/calico.yaml
          kubectl apply -f calico.yaml